name: neta_event_mvvm
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  http: ^0.13.4
  internet_connection_checker: ^0.0.1+3
  dartz: ^0.10.1
  flutter_bloc: ^8.1.1
  flutter_offline: "^2.1.0"
  bottom_navy_bar: ^6.0.0
  shared_preferences: ^2.0.15
  calendar_date_picker2: ^0.2.5
  custom_slider: ^0.0.3
  flutter_custom_tab_bar: ^1.2.0
  flutter_svg: ^1.1.5
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:



  uses-material-design: true
  assets:
    - assets/
    - assets/SlashScreen/
    - assets/icon_add_event/
    - assets/icon_user/
    - assets/packs_bg/
    - assets/packs_bg/Gold.png
    - assets/ticket/imageticket.png
    - assets/ticket/
    - assets/splash_screen/
    - assets/splash_screen/Logo.png
    - assets/intro/imagescreen1.png
    - assets/intro/

    
    
    
    
   

    


 
