name: neta_event_mvvm
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.5
  animate_do: any
  bottom_navy_bar: ^6.0.0
  calendar_date_picker2: ^0.2.5
  custom_slider: ^0.0.3
  email_validator: ^2.0.1
  flutter:
    sdk: flutter
  flutter_advanced_networkimage_2: ^2.0.1
  flutter_bloc: ^8.1.1
  flutter_custom_tab_bar: ^1.2.0
  flutter_offline: ^2.1.0
  flutter_svg: ^1.1.5
  get: ^4.6.5
  http:
  image_picker: ^0.8.6
  image_cropper: ^2.0.3
  internet_connection_checker: ^0.0.1+3
  shared_preferences: ^2.0.15
  smooth_page_indicator: ^1.0.0+2
  webview_flutter: ^3.0.4
  flutter_custom_switch: ^0.0.3
  flutter_cache_manager: ^3.3.0
  cached_network_image: ^3.2.3
  jwt_decode: ^0.3.1
  provider:
  rename: ^2.1.1
  dartz: ^0.10.1





  
  
dev_dependencies:

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.11.0"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/image/play_store_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/image/play_store_logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/image/play_store_logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/image/play_store_logo.png"

flutter:

  uses-material-design: true
  assets:
    - assets/icons/authentification/
    - assets/icon_add_event/
    - assets/gif/
    - assets/icon_user/
    - assets/packs_bg/
    - assets/image/intro/
    - assets/icons/home/ 
    - assets/icons/packe/  
    - assets/icons/splashScreen/ 
    - assets/icons/event/
    - assets/icons/tontine/    
    - assets/icons/user/        
    - assets/icons/payment/ 
    - assets/icons/notification/ 
    - assets/image/

  fonts:
    - family: AirbnbCereal
      fonts:
        - asset: fonts/AirbnbCereal_W_Md.otf
          weight: 500 
        - asset: fonts/AirbnbCereal_W_Bk.otf
          weight: 400 
        - asset: fonts/AirbnbCereal_W_Lt.otf
          weight: 300 





         # style: italic
    # - family: Trajan Pro
    #   fonts:
    #     - asset: fonts/TrajanPro.ttf
    #     - asset: fonts/TrajanPro_Bold.ttf
    #       weight: 400 
